#!/usr/bin/env node
// Bundle src/index.js → dist/worker.js for NodeGet js-worker (QuickJS).
// Settings follow https://nodeget.com/guide/js-worker/coding-guide.html:
//   bundle:true, format:"esm", platform:"browser", target:"es2022", minify:false
//
// Usage:
//   node build.mjs              one-shot build
//   node build.mjs --watch      rebuild on change

import * as esbuild from "esbuild";
import { readFileSync, writeFileSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const entry = path.join(here, "src", "index.js");
const outfile = path.join(here, "dist", "worker.js");
const watch = process.argv.includes("--watch");

const opts = {
  entryPoints: [entry],
  outfile,
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  minify: false,
  sourcemap: false,
  legalComments: "none",
  logLevel: "info",
  banner: {
    js: "// nodeget-cloudflare-ddns — generated by build.mjs. Do not edit by hand.",
  },
};

function reportSize() {
  try {
    const sz = statSync(outfile).size;
    const head = readFileSync(outfile, "utf8").split("\n").slice(0, 2).join("\n");
    console.log(`[build] dist/worker.js — ${sz} bytes`);
    console.log(`[build] head:\n${head}`);
  } catch (e) {
    console.error("[build] outfile missing:", e.message);
  }
}

if (watch) {
  const ctx = await esbuild.context(opts);
  await ctx.watch();
  console.log("[build] watching src/ — Ctrl-C to stop");
} else {
  await esbuild.build(opts);
  reportSize();
}
